### ISSUE TITLE
[Bug] Since 1.18.3, this mod make the game extremely laggy somehow.

### ISSUE THREAD

**Issue by A-plou** [kinsi55/BeatSaber_SmoothedController#1]
update the game yesterday and since no mod should of break, I shouldn'T have any problem but then I show display error on steamVR so I check in game and the game was extremely laggy.
- I insalled all the mod I had (see pictures 1 and 2) on mod assistant and all worked.
- I put some other mod (Hitbloq, Hitsoundshanger and smooth controller)
- Lag again
- removed Smooth Controller only
- All fixed
![image](https://user-images.githubusercontent.com/73841814/140545316-66f78f0f-c104-4109-b856-1121ff470ef1.png)
![image](https://user-images.githubusercontent.com/73841814/140545385-34227b03-a882-40ed-9944-634b85ec6be5.png)
[2021.11.05.00.57.25.log.gz]
(https://github.com/kinsi55/BeatSaber_SmoothedController/files/7487514/2021.11.05.00.57.25.log.gz)

logs file included.

Additionnal information: 
Windows 11
GPU: gtx 1660ti
CPU: i5 9600
RAM: 16gb
Stockage avalaible: 1tb (1.5tb total)

**Comment by kinsi55** [comment]
This doesnt make sense and I havent had any person who is using SmoothedController / updated tell me that yet but if I should have an update I'll let you know

I noticed however that you are using Windows 11, which is known to have issues with SteamVR so far. This sounds like a dumb fix but try to focus the main steam window instead of the game while playing.

**Comment by A-plou** [comment]
What do you mean by the main steam windows? 
and also, I don't have any issue with windows 11 with VR, that just happen with this mod and idk why plus I had windows 11 with 1.18.2 and it worked fine with the mod so idk what happen.

**Comment by kinsi55** [comment]
Like when playing, have the Steam window active / selected on the desktop, not beat saber.

**Comment by A-plou** [comment]
I only had Beat Saber activated that time, the only way I saw the problem was inside the headset or on the graph on steam vr little windows. Other than that I always close the Steam window and any other window.

**Comment by kinsi55** [comment]
Yes exactly, thats why I said it sounds stupid: Keep the main Steam window open and keep that selected.

**Comment by A-plou** [comment]
with further investigation and a lot of testing. It seem that I can't have any other task open beside Beat Saber on my windows screen. Not even discord. 
So it's not a mod problem, well I don't think so. 
maybe a windows 11 problem or a steamVR problem? 
it's still extremely weird of how it happening and why because sometimes I have chrome open and it didn't happen or Steam open and didn'T happen, but discord have this problem each time and the other one only happen a few time? It seem very weird.
- also I tested with and without the mod so it's not a related issue in here

**Comment by A-plou** [comment]
Pictures to illustrated the lag.
![image](https://user-images.githubusercontent.com/73841814/140564123-de49c55a-4ad7-4996-a3af-dfebbfe62f8c.png)

**Comment by kinsi55** [comment]
Yep, that exactly is the Windows 11 issue

**Comment by A-plou** [comment]
probably have a fix coming soon or a way to fix it.
